name: preprocessor
author: Christophe Hurpeau <christophe@hurpeau.com>
version: 0.2.0
homepage: https://github.com/christophehurpeau/dart-preprocessor
description: Preprocessor
documentation: http://christophehurpeau.github.io/dart-preprocessor/
environment:
  sdk: '>=1.1.0 <2.0.0'
dependencies:
  mutable_string: '>=0.2.0 <0.3.0'
  unittest: '>=0.10.0 <0.11.0'
